//
// Created by USER on 18/06/2026.
//

#ifndef STREAMERSPOLIMORFISMOYLISTAS_2025_2_METRICABASICA_H
#define STREAMERSPOLIMORFISMOYLISTAS_2025_2_METRICABASICA_H


class MetricaBasica {
};


#endif //STREAMERSPOLIMORFISMOYLISTAS_2025_2_METRICABASICA_H
