//
// Created by USER on 18/06/2026.
//

#ifndef STREAMERSPOLIMORFISMOYLISTAS_2025_2_METRICAENGAGEMENT_H
#define STREAMERSPOLIMORFISMOYLISTAS_2025_2_METRICAENGAGEMENT_H


class MetricaEngagement {
};


#endif //STREAMERSPOLIMORFISMOYLISTAS_2025_2_METRICAENGAGEMENT_H
